from distutils.core import setup, Extension

def main():
    ext_mods = [Extension("rfmix_reader.fb_reader",
                          ["rfmix_reader/fb_reader.c"]),
                ]
    setup(name="rfmix-reader",
          version="0.1.4",
          description="RFMix-reader is a Python package designed to efficiently read and process output files generated by RFMix, a popular tool for estimating local ancestry in admixed populations.",
          author="Kynon JM Benjamin",
          author_email="heartgen.lab@gmail.com",
          ext_modules=ext_mods)


if __name__ == "__main__":
    main()
